### ISSUE TITLE
What happens if two libraries use state?

### ISSUE THREAD

**Issue by awelkie** [SergioBenitez/state#1]
If two libraries (or a library and an application) use state, does their state collide or does each library get a separate state container?

**Comment by SergioBenitez** [comment]
Thanks so much for this issue. I overlooked this entirely on the first iteration. The answer in `0.1` was that the state would indeed collide. I hadn't initially considered this because I designed the library with the expectation that only private types would be stored in a container. This is a bad assumption in general, and it's too strong of a restriction to impose.

This limitation has been removed entirely. Unfortunately, it comes at the cost of now requiring nightly for its `const_fn` feature. In any case, state is now local to the binary. What's more, state need-not be static. Free free to look over the [documentation](https://sergio.bz/rustdocs/state/) for the entirely new API.

**Comment by SergioBenitez** [comment]
Closing this out. :)

Thank you, again, for this!
